import { ReceptorE5Model } from "./receptor.e5.model";
import { ReceptorB3Model } from "./receptor.b3.model";

export class ReceptorMomento2Model {
    public B1:string='';//Valida, entero, 0 ni vacio. Validar con combo box desde 0 hasta 365 y poner mayor a 365
    public B2:string='';//Validar con combo desde 0 a 125
    public lB3:ReceptorB3Model[]=[];
    public B4:ReceptorB3Model=new ReceptorB3Model();//Lista con municipios. Que el municipio esté dentro de los pasados.
    public B5:string='';//Rpta multiple, con preguntas dependientes. Validar con ventana emergente “Por favor revisar que su respuesta no esté incluida en las opciones descritas anteriormente”.    
    public B5_4_1:string='';
    public B5_4_1_otro:string='';
    public B5_5_1:string='';//Rpta multiple con pregunta dependiente
    public B5_6_1:string='';//Rpta multiple con pregunta dependiente
    public B5_6_1_otro:string='';
    public B5_8_1:string='';
    public B5_8_1_otro:string='';
    public B5_10_1:string='';
    public B5_10_1_otro:string='';
    public B5_otro:string='';
    public C1:string='';
    public C1_otro:string='';
    public C2:string='';
    public C2_otro:string='';
    public D1:string='';//Pregunta de única respuesta con combo box entre 1 y 150, además mayor a 150.Si la respuesta es uno, se marca el ítem 1 y se deshabilita el resto. Si es mayor que 1, se deshabilita la opción 1 y se habilitan las demás. Además hay pregunta dependiente en el ítem 8.Validar el otro cual con ventana emergente.
    public D2:string='';
    public D2_8_1:string='';
    public D2_otro:string='';
    public E1:string='';
    public E1_1:string='';
    public E1_1_otro:string='';
    public E2:string='';//Pendiente de definer, si es con rangos, o de única respuesta con combo box, o como quieran.
    public E2_1:string='';//Combo box entre 1 y 100
    public E3:string='';//Combo box entre 1 y 100
    public E3_1:string='';
    public E4:string='';
    public E4_otro:string='';
    public TempE5:string[]=[];
    public lE5:ReceptorE5Model[]=[];
    public E5_otro:ReceptorE5Model=new ReceptorE5Model();
    public E6:string[]=[];//Multiple rpta, 
    public E6_otro:string='';
    public E7:string='';//Abierta, es dependiente de E5 y E6; hay que activar esta pregunta cuando en E5 o E6 está seleccionado el 3(transporte terrestre).
    public E8:string='';//Única respuesta, hay que validar con E5 o E6 si está seleccionado el 5(alquiler de vehículo).
    public E9:string='';//Unica selección. Hay que validar con E5 y E6 si está seleccionado  el 12 (bienes de consumo duradero).
    public E10:string='';//Múltiple respuesta, validar el otro/cual con ventana emergente.
    public E10_otro:string='';
    public F1:string='';//Unica respuesta, con pregunta dependiente.
    public F1_1:string='';
    public F1_2:string='';
    public F1_3:string='';
    public F1_4:string='';
    public F1_5:string='';
    public F1_6:string='';
    public F1_7:string='';
    public F2:string='';
    public F2_8:string='';
    public F2_9:string='';
    public F2_10:string='';
    public F2_11:string='';
    public F2_12:string='';
    public F2_13:string='';
    public F2_14:string='';
    public F2_15:string='';
    public F2_16:string='';
    public F2_17:string='';
    public F2_18:string='';
    public F2_19:string='';
    public F2_20:string='';
    public F2_21:string='';
    public F2_22:string='';
    public F3:string='';
    public F4:string='';
    public F5:string='';
    public F6:string='';
    public F7:string='';//Unica respuesta. Poner desde 1 a 20 y opción mayor a 20
    public G1:string='';//Opción multiple y validar el otro cual con ventana emergente
    public G1_otro:string='';
    public G2:string='';//Opción multiple y validar el otro cual con ventana emergente
    public G2_otro:string='';
    public G3:string='';//Opción multiple y validar el otro cual con ventana emergente
    public G3_otro:string='';
    public G4:string='';//Opción multiple y validar el otro cual con ventana emergente
    public G4_email:string='';//Opción multiple y validar el otro cual con ventana emergente
    public G5:string='';
    public G5_facebook:string='';
    public G5_twitter:string='';
    public H1:string='';//Rpta múltiple
    public H2:string='';//Rpta múltiple
    public H3_1:string='';
    public H3_2:string='';
    public H3_3:string='';
    public H3_4:string='';
    public H3_5:string='';
    public H4:string[]=[];//Cargar el destino principal.(PB4).Varias respuestas, validamos el otro cual con la ventana emergente
    public H4_otro:string='';
    public H5:string[]=[];
    public H5_otro:string='';
    public H6:string[]=[];
    public H6_otro:string='';
    public H7:string[]=[];
    public H7_otro:string='';        
    public H8:string='';
    public H8_otro:string='';        
    public H9:string='';
    public H9_otro:string='';        
    public H10:string='';
    public H11:string='';
    public dateEnd:string='';
    public A8_1:string='';//Solo texto, sin números, ni caracteres especiales.
    public A8_2:string='';//Solo texto, sin números, ni caracteres especiales.
    public A9:string='';//Validaciones propias de correo electrónico
    public A10:string='';//Celular Buscar la forma de partir el número para que el indicativo quede aparte.
    public A11:string='';//Validaciones propias de teléfono.
}
